addSbtPlugin("com.dwijnand"      % "sbt-travisci" % "1.0.0")
addSbtPlugin("com.geirsson"      % "sbt-scalafmt" % "0.5.5")
addSbtPlugin("com.typesafe.sbt"  % "sbt-git"      % "0.8.5")
addSbtPlugin("de.heikoseeberger" % "sbt-header"   % "1.6.0")
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.3")
